_extends: .github

repository:
    description: 🍻 I3 status bar.
    homepage: https://github.com/KarolosLykos/archista
    topics: go, golang, golang, i3, i3-status, barista, barista-contrib, i3-bar
    default_branch: main
    private: false
    
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: []
      required_linear_history: true
      enforce_admins: null
      restrictions: null
