run:
  tests: false

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/KarolosLykos/archista)
#  goimports:
#    local-prefixes: github.com/KarolosLykos/archista
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  stylecheck:
    checks: ["all", "-ST1006"]
  misspell:
    locale: US,UK
  nolintlint:
    allow-leading-space: false # require machine-readable nolint directives (with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - depguard
    - dupl
    - exportloopref
    - forcetypeassert
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - goprintffuncname
    - gosec
    - misspell
    - noctx
    - nolintlint
    - stylecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - whitespace
issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gocritic
        - typecheck
    - linters:
        - gocritic
      text: "unnecessaryDefer:"

service:
  golangci-lint-version: 1.52.x # use the fixed version to not introduce new linters unexpectedly