version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - errcheck
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - noctx
    - nolintlint
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    gocyclo:
      min-complexity: 15
    nolintlint:
      require-explanation: true
      require-specific: false
      allow-unused: false
    staticcheck:
      checks:
        - all
        - -ST1006
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocritic
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - gocritic
        text: 'unnecessaryDefer:'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/KarolosLykos/archista)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
